// prototype/02/src/components/calendar/AddMealDialog.tsx
import { useState, useEffect } from "react";
import { Recipe } from "@/lib/recipe-types";
import { searchRecipes, loadTags, addTag as addTagToDb } from "@/lib/recipe-database";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Utensils, X, Plus, ChevronDown } from "lucide-react";

interface AddMealDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectRecipe: (recipe: Recipe) => void;
}

export function AddMealDialog({
  isOpen,
  onClose,
  onSelectRecipe,
}: AddMealDialogProps) {
  const [searchText, setSearchText] = useState("");
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [availableTags, setAvailableTags] = useState<string[]>([]);
  const [filteredRecipes, setFilteredRecipes] = useState<Recipe[]>([]);

  useEffect(() => {
    setAvailableTags(loadTags());
  }, []);

  useEffect(() => {
    const results = searchRecipes(
      searchText || undefined,
      selectedTags.length > 0 ? selectedTags : undefined
    );
    setFilteredRecipes(results);
  }, [searchText, selectedTags]);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    const value = searchText;
    const hashMatch = value.match(/#([\w\u00A0]+)$/);
    
    if (hashMatch) {
      const isModifierPressed = e.shiftKey || e.altKey || e.ctrlKey || e.metaKey;
      const isWordBoundary = [' ', ',', '.', ';', '!', '?', 'Enter'].includes(e.key);
      
      if (e.key === ' ' && isModifierPressed) {
        e.preventDefault();
        setSearchText(value + '\u00A0');
      } else if (isWordBoundary) {
        e.preventDefault();
        const newTag = hashMatch[1].toLowerCase();
        const updatedTags = addTagToDb(newTag);
        setAvailableTags(updatedTags);
        if (!selectedTags.includes(newTag)) {
          setSelectedTags((prev) => [...prev, newTag]);
        }
        setSearchText("");
      }
    }
  };

  const handleSearchChange = (value: string) => {
    setSearchText(value);
  };

  const handleTagSelect = (tag: string) => {
    if (!selectedTags.includes(tag)) {
      setSelectedTags((prev) => [...prev, tag]);
    }
  };

  const handleTagRemove = (tag: string) => {
    setSelectedTags((prev) => prev.filter((t) => t !== tag));
  };

  const handleSelect = (recipe: Recipe) => {
    onSelectRecipe(recipe);
    onClose();
  };

  const handleClose = () => {
    setSearchText("");
    setSelectedTags([]);
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Add a Meal</DialogTitle>
        </DialogHeader>
        
        <div className="space-y-3">
          <Input
            type="text"
            placeholder="Search recipes or type #ingredient..."
            value={searchText}
            onChange={(e) => handleSearchChange(e.target.value)}
            onKeyDown={handleKeyDown}
            className="w-full"
          />

          <div className="flex items-center gap-2">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm" className="gap-1">
                  <Plus className="h-4 w-4" />
                  Ingredient
                  <ChevronDown className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="start">
                {availableTags.map((tag) => (
                  <DropdownMenuItem
                    key={tag}
                    onClick={() => handleTagSelect(tag)}
                    disabled={selectedTags.includes(tag)}
                  >
                    {tag.replace(/\u00A0/g, ' ')}
                  </DropdownMenuItem>
                ))}
              </DropdownMenuContent>
            </DropdownMenu>

            <div className="flex flex-wrap gap-2">
              {selectedTags.map((tag) => (
                <Badge key={tag} variant="secondary" className="gap-1 pr-1">
                  {tag.replace(/\u00A0/g, ' ')}
                  <button
                    onClick={() => handleTagRemove(tag)}
                    className="ml-1 hover:bg-gray-300 rounded-full p-0.5"
                  >
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-2 h-[400px] overflow-y-auto mt-4">
          {filteredRecipes.map((recipe) => (
            <button
              key={recipe.title}
              onClick={() => handleSelect(recipe)}
              className="w-full flex items-center gap-3 p-3 rounded-lg hover:bg-gray-50 transition-colors border border-gray-100"
            >
              <div className="w-10 h-10 bg-gray-100 rounded-lg flex items-center justify-center flex-shrink-0">
                <Utensils className="w-5 h-5 text-gray-600" />
              </div>
              <div className="flex-1 text-left">
                <div className="font-medium text-gray-900">{recipe.title}</div>
                <div className="text-sm text-gray-500">{recipe.total_time} min</div>
              </div>
            </button>
          ))}
          {filteredRecipes.length === 0 && (
            <div className="text-center py-8 text-gray-500">
              No recipes found
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

// apps/web/src/lib/components/AddMealDialog.svelte
<script lang="ts">
  import { writable, derived } from 'svelte/store'
  import { searchQuery, selectedTags, availableTags, filteredRecipes, setSearchQuery, addTag, removeTag, createNewTag } from '$lib/stores/recipes'
  import type { Recipe } from '@mealplanner/recipe-database'
  
  export let date: Date
  export let onClose: () => void
  export let onSelectRecipe: (recipe: Recipe) => void
  
  let showIngredientDropdown = false
  
  function normalizeTagLabel(tag: string): string {
    return tag.replace(/\u00A0/g, ' ')
  }
  
  function handleKeyDown(event: KeyboardEvent) {
    const target = event.target as HTMLInputElement
    const hashMatch = target.value.match(/#([\w\u00A0]+)$/)
    
    if (!hashMatch) return

    const isModifierPressed = event.shiftKey || event.altKey || event.ctrlKey || event.metaKey
    const isWordBoundary = [' ', ',', '.', ';', '!', '?', 'Enter'].includes(event.key)

    if (event.key === ' ' && isModifierPressed) {
      event.preventDefault()
      setSearchQuery($searchQuery + '\u00A0')
      return
    }

    if (isWordBoundary) {
      event.preventDefault()
      const newTag = (hashMatch[1] ?? '').toLowerCase()
      createNewTag(newTag)
      setSearchQuery('')
    }
  }
  
  function toggleIngredientDropdown() {
    showIngredientDropdown = !showIngredientDropdown
  }
  
  function selectIngredient(tag: string) {
    addTag(tag)
    showIngredientDropdown = false
  }
  
  function handleSelectRecipe(recipe: Recipe) {
    onSelectRecipe(recipe)
    setSearchQuery('')
    selectedTags.set([])
  }
</script>

<!-- Backdrop -->
<div 
  class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4"
  on:click={onClose}
  on:keydown={(e) => e.key === 'Escape' && onClose()}
  role="presentation"
>
  <!-- Dialog -->
  <div 
    class="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[80vh] flex flex-col"
    on:click|stopPropagation
    role="dialog"
    aria-modal="true"
    aria-labelledby="dialog-title"
  >
    <!-- Header -->
    <div class="px-6 py-4 border-b border-gray-200">
      <h2 id="dialog-title" class="text-xl font-semibold text-gray-900">Add a Meal</h2>
    </div>
    
    <!-- Search Section -->
    <div class="px-6 py-4 border-b border-gray-100 space-y-3">
      <!-- Search Input -->
      <input
        type="text"
        value={$searchQuery}
        on:input={(e) => setSearchQuery(e.currentTarget.value)}
        on:keydown={handleKeyDown}
        placeholder="Search recipes or type #ingredient..."
        class="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        autofocus
      />
      
      <!-- Ingredient Dropdown Trigger & Selected Tags -->
      <div class="flex items-center gap-2 flex-wrap">
        <div class="relative">
          <button
            type="button"
            on:click={toggleIngredientDropdown}
            class="inline-flex items-center gap-2 px-3 py-1.5 border border-gray-300 rounded-lg hover:bg-gray-50 transition"
          >
            <svg class="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
            </svg>
            <span class="text-sm text-gray-700">Ingredient</span>
            <svg class="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"/>
            </svg>
          </button>
          
          <!-- Dropdown Menu -->
          {#if showIngredientDropdown}
            <div class="absolute top-full left-0 mt-1 bg-white border border-gray-200 rounded-lg shadow-lg py-1 min-w-[150px] z-10">
              {#each $availableTags as tag}
                <button
                  type="button"
                  on:click={() => selectIngredient(tag)}
                  class="w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 transition"
                >
                  {normalizeTagLabel(tag)}
                </button>
              {/each}
            </div>
          {/if}
        </div>
        
        <!-- Selected Tags -->
        {#each $selectedTags as tag}
          <span class="inline-flex items-center gap-2 bg-blue-50 text-blue-700 px-3 py-1 rounded-lg text-sm">
            {normalizeTagLabel(tag)}
            <button
              type="button"
              on:click={() => removeTag(tag)}
              class="hover:bg-blue-100 rounded-full p-0.5 transition"
              aria-label="Remove {normalizeTagLabel(tag)}"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
              </svg>
            </button>
          </span>
        {/each}
      </div>
    </div>
    
    <!-- Recipe List -->
    <div class="flex-1 overflow-y-auto px-6 py-4">
      <div class="space-y-2">
        {#if $filteredRecipes.length === 0}
          <div class="text-center py-8 text-gray-500">
            No recipes found. Try adjusting your search.
          </div>
        {:else}
          {#each $filteredRecipes as recipe}
            <button
              type="button"
              on:click={() => handleSelectRecipe(recipe)}
              class="w-full flex items-center gap-3 p-3 hover:bg-gray-50 rounded-lg transition text-left group"
            >
              <!-- Recipe Icon -->
              <div class="flex-shrink-0 w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center">
                <svg class="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
                </svg>
              </div>
              
              <!-- Recipe Info -->
              <div class="flex-1 min-w-0">
                <div class="font-medium text-gray-900">{recipe.title}</div>
                <div class="text-sm text-gray-600">{recipe.total_time} min</div>
              </div>
            </button>
          {/each}
        {/if}
      </div>
    </div>
    
    <!-- Footer -->
    <div class="px-6 py-4 border-t border-gray-200">
      <button
        type="button"
        on:click={onClose}
        class="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-gray-100 hover:bg-gray-200 rounded-lg transition font-medium text-gray-700"
      >
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
        </svg>
        <span>Close</span>
      </button>
    </div>
  </div>
</div>
